### ISSUE TITLE
install Web RTL

### ISSUE THREAD

**Issue by saeedghx68** [barsi/odoo-rtl#11]
hi
How to install Web RTL module?

I do this level 
        go to settings => language and make sure your target                language (e.g. arabic) is Right to left direction.
in your wiki 

and don't see Web RTL module in the Local Module

and so ...
odoo-server.conf is set to: addons_path = /opt/odoo/addons
I checked log and see:
WARNING printx openerp.models: Cannot execute name_search, no _rec_name defined on base.module.update

Best Regard

**Comment by mrawi** [comment]
1- Download the modules.
2- Copy them to your addons path
3- check access rights and files ownership (specially if you are using *nix systems).
4- In Odoo, Settings menu, click 'Update Modules List'
5- Search for RTL and install the modules.

The warning you see is not related to the RTL modules.

**Comment by nisim** [comment]
This instructions to install is for odoo 9 too ??
