### ISSUE TITLE
Report RTL not working

### ISSUE THREAD

**Issue by heshamfm** [barsi/odoo-rtl#12]
setup instructions say:
`if your report still in LTR, make sure that the report is not depends on Partner's language (e.g. Invoice Reports, Sale report). or review steps of backend UI`

What is meant by `not depends on Partner's language` and how can I correct that?

**Comment by mrawi** [comment]
You can set a default mailing language on partners. On a partner's form view, the 'Sales & Purchases' tab, you'll find 'Language' field. Set it to Arabic.

This field affects reports' language like sales orders, invoices, etc.
