### ISSUE TITLE
website_rtl is not working with odoo9

### ISSUE THREAD

**Issue by manutvarghese** [barsi/odoo-rtl#19]
website_rtl was not working with odoo9

**Comment by ahmedfh** [comment]
It is work find with me but It does not have any icons in the display.

**Comment by nisim** [comment]
it eorks in odoo9 ?
how to install in odoo9?

**Comment by nisim** [comment]
it work in odoo9 ?
how to install in odoo9 ?

**Comment by aymenrahmaniisims** [comment]
RTL work correctly with the community version but for the enterprise version NO

**Comment by barsi** [comment]
this repo is to provide rtl support only for odoo community version
