### ISSUE TITLE
Date and Datetime filed error

### ISSUE THREAD

**Issue by abdallamohamed1992** [barsi/odoo-rtl#25]
Hello

I can not open calendar in one2many because calendar button hidden 

attached image from purchase order line

![date error](https://cloud.githubusercontent.com/assets/13385546/19305990/d530659e-9073-11e6-8382-520d490a912f.PNG)

**Comment by abdallamohamed1992** [comment]
In version 8

**Comment by barsi** [comment]
fixed in commit 1987aff
