### ISSUE TITLE
odoo 12

### ISSUE THREAD

**Issue by j209** [barsi/odoo-rtl#35]
Hi
When the module will be ready for odoo 12?

**Comment by naydi-nebras** [comment]
I'm waiting too ..

**Comment by majeedid** [comment]
We all are waiting ...

**Comment by JeelBKhanpara** [comment]
hi i have migrated module for odoo 12.

**Comment by j209** [comment]
In version 12 enterprise edition rtl feuture is active out of the box.[Odoo 12 new features](https://webkul.com/blog/webkul-odoo-12/)
![image](https://user-images.githubusercontent.com/18129232/50397205-07d52f00-0784-11e9-9e2c-64413d6b0246.png)

**Comment by kahtooei** [comment]
how do i use this module for odoo 12 community ???????
why aren't there any rtl module for odoo 12 ?????

**Comment by JeelBKhanpara** [comment]
> how do i use this module for odoo 12 community ???????
> why aren't there any rtl module for odoo 12 ?????

share your id i will provide you.

**Comment by kahtooei** [comment]
> 
> 
> > how do i use this module for odoo 12 community ???????
> > why aren't there any rtl module for odoo 12 ?????
> 
> share your id i will provide you.

thanks
but which id i have to share?
my email: mcheeff@gmail.com

**Comment by j209** [comment]
https://github.com/odoo/odoo/issues/29958

**Comment by eranetsa** [comment]
> > how do i use this module for odoo 12 community ???????
> > why aren't there any rtl module for odoo 12 ?????
> 
> share your id i will provide you.

y@letsw.com
thanks

**Comment by mart-e** [comment]
Hi,

Odoo developer here. The rtl interface is available in Odoo 12.0, both community and enterprise (not sure why people thought it was enterprise only).
However, if you are using Odoo on your own server, please don't forget to check [installation documentation](https://www.odoo.com/documentation/12.0/setup/install.html#id3).
Unlike in v11, you will need to install the package [rtlcss](https://rtlcss.com/) to make it work.

If you have already installed Odoo but not rtlcss, you will need to invalidate the assets to make it work (or check the page in debug=assets mode).

This module is still useful for v11 as the change was only in the newest version.

**Comment by j209** [comment]
Hi
I have installed rtlcss and odoo12 on my own server(win 10)  but the problem not solved.
Please guide us step by step for this

![image](https://user-images.githubusercontent.com/18129232/50841551-348b6800-137a-11e9-982e-e7900a3d576c.png)

![image](https://user-images.githubusercontent.com/18129232/50841575-43721a80-137a-11e9-9e7b-e8150b2dd608.png)

**Comment by kahtooei** [comment]
> 
> 
> Hi,
> 
> Odoo developer here. The rtl interface is available in Odoo 12.0, both community and enterprise (not sure why people thought it was enterprise only).
> However, if you are using Odoo on your own server, please don't forget to check [installation documentation](https://www.odoo.com/documentation/12.0/setup/install.html#id3).
> Unlike in v11, you will need to install the package [rtlcss](https://rtlcss.com/) to make it work.
> 
> If you have already installed Odoo but not rtlcss, you will need to invalidate the assets to make it work (or check the page in debug=assets mode).
> 
> This module is still useful for v11 as the change was only in the newest version.

thank you very much
after installing npm and rtlcss it works very well
now it's ok for rtl languages

**Comment by kahtooei** [comment]
another thing...
how can i change font only for rtl languages?
the default font for languages like arabic and persien is not beautiful

**Comment by j209** [comment]
> another thing...
> how can i change font only for rtl languages?
> the default font for languages like arabic and persien is not beautiful

Edit this file
\\Odoo 12.0\server\odoo\addons\web\static\src\scss\bootstrap_overridden.scss
