### ISSUE TITLE
[8] report_rtl module hide footer Odoo

### ISSUE THREAD

**Issue by Sameer1990** [barsi/odoo-rtl#9]
It seems when i install report_rtl module it will hide the footer from all reports , in the other hand when uninstall report_rtl the footer is back to shown on all reports.

**Comment by majeedid** [comment]
Yes, that is right, it does hide the footer when report_rtl module installed!!!, it happens for me also, and we still waiting a contribution here of the guys who have made this solution to know whether this could be resolved sooner.

**Comment by Sameer1990** [comment]
Hi,
Wkhtmltopdf version 0.12.2 and 0.12.2.1 seems to have some regressions: --dpi ignored and javascript links not processed.

You should use wkhtmltopdf 0.12.1

Regards
